[package]
name = "gba-emulator"
version = "0.1.0"
authors = ["Akash Munagala <akash.munagala@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "core" }
imgui-glfw-rs = "0.4.1"
gl = "0.14.0"
