[package]
name = "gba-emulator"
version = "0.1.0"
authors = ["Akash Munagala <akash.munagala@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "core" }
imgui = "0.3.0"
imgui-opengl-renderer = "0.7.0"
gl = "0.14.0"
glfw = "0.37.0"
