[package]
name = "core"
version = "0.1.0"
authors = ["Akash Munagala <akash.munagala@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
flume = "0.7.1"
log = "0.4.8"
num = "0.3.0"
simplelog = "0.8.0"

[profile.release]
debug = true
